//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int CalendarEventId { get; set; }
        public int StaffId { get; set; }
        public string Title { get; set; }
        public string Priority { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
