//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.Case_Customer = new HashSet<Case_Customer>();
            this.Case_Staff = new HashSet<Case_Staff>();
            this.Payments = new HashSet<Payment>();
            this.Subjects = new HashSet<Subject>();
            this.UsedServices = new HashSet<UsedService>();
            this.OperationalEvents = new HashSet<OperationalEvent>();
        }
    
        public int CaseId { get; set; }
        public string CaseCode { get; set; }
        public int CreatorId { get; set; }
        public int OfficeId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string Status { get; set; }
        public string CaseContent { get; set; }
        public string DisputeSubject { get; set; }
        public string DisputeRelation { get; set; }
        public string LimitationStatute { get; set; }
        public string LegalEvent { get; set; }
        public string ErrorFactor { get; set; }
        public string ProtectiveGoal { get; set; }
        public string OpeningProcedure { get; set; }
        public string InquiryProcedure { get; set; }
        public string ArgumentProcedure { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Case_Customer> Case_Customer { get; set; }
        public virtual ICollection<Case_Staff> Case_Staff { get; set; }
        public virtual Office Office { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<UsedService> UsedServices { get; set; }
        public virtual ICollection<OperationalEvent> OperationalEvents { get; set; }
    }
}
