//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Case_Customer = new HashSet<Case_Customer>();
        }
    
        public int CustomerId { get; set; }
        public int CustomerGroupId { get; set; }
        public string CustomerName { get; set; }
        public string Representative { get; set; }
        public string TaxCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string BankAccount { get; set; }
        public string BankBranch { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Case_Customer> Case_Customer { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
    }
}
