//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office_Staff
    {
        public int OfficeStaffId { get; set; }
        public int OfficeId { get; set; }
        public int StaffId { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
