//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryAssuranceDetail
    {
        public int ID { get; set; }
        public int SalaryID { get; set; }
        public int AssuranceID { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual Assurance Assurance { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
