//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffGroup
    {
        public StaffGroup()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int StaffGroupId { get; set; }
        public string StaffGroupName { get; set; }
        public string Description { get; set; }
        public Nullable<double> BaseSalary { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
