//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformation
    {
        public int StaffInformationId { get; set; }
        public int StaffId { get; set; }
        public string Avatar { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string IdentityNumber { get; set; }
        public System.DateTime IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public string TaxCode { get; set; }
        public string BankAccount { get; set; }
        public string BankBranch { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
