//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public Tax()
        {
            this.SalaryTaxDetails = new HashSet<SalaryTaxDetail>();
        }
    
        public int TaxID { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public double IndexTax { get; set; }
        public bool Active { get; set; }
        public double MoneyFrom { get; set; }
        public double MoneyTo { get; set; }
    
        public virtual ICollection<SalaryTaxDetail> SalaryTaxDetails { get; set; }
    }
}
