//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int ID { get; set; }
        public int StaffId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public double Hours { get; set; }
        public bool IsAllowed { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
