//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assurance
    {
        public Assurance()
        {
            this.SalaryAssuranceDetails = new HashSet<SalaryAssuranceDetail>();
        }
    
        public int AssuranceID { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<SalaryAssuranceDetail> SalaryAssuranceDetails { get; set; }
    }
}
