//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public Benefit()
        {
            this.SalaryBenefitDetails = new HashSet<SalaryBenefitDetail>();
        }
    
        public int BenefitID { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<SalaryBenefitDetail> SalaryBenefitDetails { get; set; }
    }
}
