//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalEvent
    {
        public int OperationalEventId { get; set; }
        public int CaseId { get; set; }
        public int CreatorId { get; set; }
        public string Title { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
