//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public Salary()
        {
            this.SalaryAssuranceDetails = new HashSet<SalaryAssuranceDetail>();
            this.SalaryBenefitDetails = new HashSet<SalaryBenefitDetail>();
            this.SalaryTaxDetails = new HashSet<SalaryTaxDetail>();
        }
    
        public int SalaryID { get; set; }
        public System.DateTime Date { get; set; }
        public int StaffId { get; set; }
        public double TotalAbsent { get; set; }
        public double TotalPresent { get; set; }
        public double TotalBenefit { get; set; }
        public double TotalImprest { get; set; }
        public double TotalTax { get; set; }
        public double TotalAssurance { get; set; }
        public double TotalReward { get; set; }
        public double BaseSalary { get; set; }
        public double ActualSalary { get; set; }
        public bool Active { get; set; }
        public double TotalDateDeduction { get; set; }
        public double TotalMoneyDeduction { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual ICollection<SalaryAssuranceDetail> SalaryAssuranceDetails { get; set; }
        public virtual ICollection<SalaryBenefitDetail> SalaryBenefitDetails { get; set; }
        public virtual ICollection<SalaryTaxDetail> SalaryTaxDetails { get; set; }
    }
}
